### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'neat-checkpoint-601'

### ISSUE THREAD

**Issue by SgtMarmite** [Vedant-Gupta523/sonicNEAT#2]
I am running into the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'neat-checkpoint-601'

What is the following code doing? Could anyone explain?

```
if resume == True:
    p = neat.Checkpointer.restore_checkpoint(restore_file)
else:
    p = neat.Population(config)
```

**Comment by SgtMarmite** [comment]
I have resolved the issue by commenting out a part of the code like this:
```
if resume == True:
#    p = neat.Checkpointer.restore_checkpoint(restore_file)
#else:
    p = neat.Population(config)
```

The code then ran and after first iteration saved the neat-checkpoint-0 in the root folder.
I proceeded with editing the restore_file variable to 'neat-checkpoint-0'.
Then I uncommented the code above and the code is now working.

**Comment by aaronbalzac** [comment]
Hey man , can you send me the neat-checkpoint-0 file,my system is not producing the file even after running the iteration once.

**Comment by SgtMarmite** [comment]
There you go

Dne pá 2. srp 2019 9:36 uživatel aaronbalzac <notifications@github.com>
napsal:

**Comment by SgtMarmite** [comment]
[sonic.zip](https://github.com/Vedant-Gupta523/sonicNEAT/files/3461451/sonic.zip)

**Comment by aaronbalzac** [comment]
thanks man. Appreciate it
